class DEVELOPMENT_CONFIGURATIONS:
    DEBUG = True
    SECRET_KEY = "ferfrfrf343434g"
    TEMPLATES_FOLDER = "./frontend/templates"
    STATICS_FOLDER = "./frontend/statics"
    TEMP_COUNTDONW_FOCUS_MINUTES = 3
    TEMP_COUNTDOWN_FOCUS_SECONDS = 0
    TEMP_COUNTDONW_SHORTREST_MINUTES = 1
    TEMP_COUNTDONW_LONGREST_MINUTES = 2
    TEMP_COUNTDOWN_LAPS = 3